# Generated by Django 5.2.7 on 2025-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='dispositivos.zone'),
        ),
    ]
