# Generated by Django 5.2.7 on 2025-10-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_zones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='zones',
        ),
    ]
