# Generated by Django 5.2.7 on 2025-10-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_remove_zone_created_at'),
        ('organizations', '0003_remove_organization_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='dispositivos.zone'),
        ),
    ]
