# Generated by Django 5.2.7 on 2025-10-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
