# Generated by Django 5.2.7 on 2025-10-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_zone_created_at_alter_zone_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='created_at',
        ),
    ]
